### PR TITLE
Made this compatible with cmake version 3.5.1

### PR DESCRIPTION
**Pull request by stazio**

### CODE REVIEW

**Comment by mstorsjo** [comment]
@evpobr What's your take on this one? Did the cmake project file use any features that require the minimum to be set to 3.10, or was it just for convenience of testing?

**Comment by evpobr** [comment]
> Did the cmake project file use any features that require the minimum to be set to 3.10

I choose a more or less distributed version for new projects. It seems to me that nothing prevents you from lowering the level to 3.5.1. I usually check poular CMake versions here: https://repology.org/project/cmake/information.

> What's your take on this one

Ok.

**Comment by mstorsjo** [comment]
> > Did the cmake project file use any features that require the minimum to be set to 3.10
> 
> I choose a more or less distributed version for new projects. It seems to me that nothing prevents you from lowering the level to 3.5.1. I usually check poular CMake versions here: https://repology.org/project/cmake/information.
> 
> Should i create pull request?

This is already a pull request that lowers it to 3.5.1.

**Comment by evpobr** [comment]
Uh, ok.

**Pull request merged**
