### PR TITLE
DAB+ support (960 transform)

### PR DESCRIPTION
**Pull request by mpbraendli**
Hi Martin,
we are currently using fdk-aac for DAB+ encoding with the www.opendigitalradio.org tools, specifically with https://github.com/Opendigitalradio/ODR-AudioEnc
DAB+ allows (but does not require) SBR and PS, but with some differences most importantly the 960 transform size.
The 960 transform could be useful for Digital Radio Mondiale too, but more work would probably be needed to output a valid data stream for that.

### CODE REVIEW

**Comment by mstorsjo** [comment]
First, sorry for the late reply.

Is this a rebased/updated/cleaned up version of what's in https://github.com/piratfm/fdk-aac-dabplus, or what's the relationship between those?

In general, as you probably know, I'm quite wary of merging extra changes outside of build system stuff and bug fixes, to avoid diverging too far from the upstream, to simplify maintainance when new upstream releases are made. Ideally, it'd be best if this code could be merged upstream (either in AOSP, or directly to Fraunhofer). Although I do realize that it's pretty unlikely that it'll get accepted there.

I guess these commits are quite much cleaned up compared to the original version, but there's still quite a bit of leftover noise; commented out debugging statements, extra `#if 1`, etc, and a duplicate bootstrap script (we've got `autogen.sh` now). Without giving any promise about merging it, it'd improve the chances of it getting further if all those are cleaned up as well, so that the pull request doesn't contain any extra unrelated changes at all.

**Comment by mpbraendli** [comment]
Hi

Yes, this contains the work from piratfm and some additional changes to support Programme-Associated Data insertion. I've not been able to rework in a way that kept the original commits, because of the reorganisation: We had our front-end tool in the same repository for quite a while, and now I split it off into ODR-AudioEnc.

I understand that you want to follow the AOSP version closely, and I would be surprised if they were interested in the features we want to add.

Now that the history has been cleaned up a bit, it's going to be easier to follow changes in our fork. Thanks for looking into the question!

**Comment by mstorsjo** [comment]
Thanks for your understanding!

Yes, with the changes cleaned up, it's probably easier to maintain when going forward.

As for maintaining this kind of changes, I can warmly recommend the approach I'm using here in fdk-aac; the master branch moves forward with incremental changes and merges from upstream. This is what normal people would use, allowing you to easily see what has changed from what you had before to the latest. Separately, I maintain a second branch named `upstream-patched`, with a linear set of patches rebased on top of the latest upstream master (in my case, AOSP master). The actual file content in this branch is identical to the normal master (e.g. `git diff master upstream-patched` shows no changes).

So whenever I e.g. do a change to, say, `Makefile.am` on the master branch, I cherrypick the same change into the upstream-patched branch, and if relevant, squash into the commit named "Add autotools build system". That way, it's easy to see exactly in which way my repo differs from the upstream, with as few changes as possible. And in case some of the local fixes are upstreamable, it will even reduce my number of patches.

Then when the upstream has got a lot of changes, possibly conflicting with my local changes, it's easy to doublecheck that the merge ended up right, when trying to rebase this upstream-patched branch, and seeing if the local change that I had really makes sense any longer on top of the new upstream, or if that change should be done in a different way now to achieve the same.

**Comment by mstorsjo** [comment]
In my case, the changes on the upstream-patched branch are split to keep it readable. All of the autotools/examples patch is basically the gist of this repo, things that upstream definitely doesn't want. Some of the other commits are minor changes and fixes that possibly could make sense to upstream, but which they still probably aren't interested enough in taking, or some that I've tried to upstream but they haven't yet merged. Some of them have even been fixes from Fraunhofer, that will appear in future AOSP versions (which took quite some time to appear there though).

**Comment by mpbraendli** [comment]
Ok, now I understand the meaning of the different branches a bit better. I will regularly merge your master branch into my dabplus branch (which is the default branch in the fork, it makes its meaning a tad more obvious).

I will also add a README to my fork explaining the relationship between the repositories.

**Pull request closed without merging**
